// //
// //  Generated by the J2ObjC translator.  DO NOT EDIT!
// //  source: None::com/squareup/protos/common/CurrencyCode.java
// //

// #include <J2objcRuntime/J2ObjC_header.h>

// #pragma push_macro("INCLUDE_ALL_ComSquareupProtosCommonCurrencyCode")
// #ifdef RESTRICT_ComSquareupProtosCommonCurrencyCode
// #define INCLUDE_ALL_ComSquareupProtosCommonCurrencyCode 0
// #else
// #define INCLUDE_ALL_ComSquareupProtosCommonCurrencyCode 1
// #endif
// #undef RESTRICT_ComSquareupProtosCommonCurrencyCode

// #if __has_feature(nullability)
// #pragma clang diagnostic push
// #pragma GCC diagnostic ignored "-Wnullability-completeness"
// #endif

// #if !defined (ComSquareupProtosCommonCurrencyCode_) && (INCLUDE_ALL_ComSquareupProtosCommonCurrencyCode || defined(INCLUDE_ComSquareupProtosCommonCurrencyCode))
// #define ComSquareupProtosCommonCurrencyCode_

// #define RESTRICT_JavaLangEnum 1
// #define INCLUDE_JavaLangEnum 1
// #include <J2objcRuntime/java/lang/Enum.h>

// #define RESTRICT_ExternalWireWire_runtimeSrcMainJavaComSquareupWireWireEnum 1
// #define INCLUDE_ComSquareupWireWireEnum 1
// #include <WireShared/external/wire/wire-runtime/src/main/java/com/squareup/wire/WireEnum.h>

// @class ComSquareupProtosCommonDenominations;
// @class ComSquareupWireProtoAdapter;
// @class IOSObjectArray;
// @class JavaLangInteger;

// typedef NS_ENUM(NSUInteger, ComSquareupProtosCommonCurrencyCode_Enum) {
//   ComSquareupProtosCommonCurrencyCode_Enum_AED = 0,
//   ComSquareupProtosCommonCurrencyCode_Enum_AFN = 1,
//   ComSquareupProtosCommonCurrencyCode_Enum_ALL = 2,
//   ComSquareupProtosCommonCurrencyCode_Enum_AMD = 3,
//   ComSquareupProtosCommonCurrencyCode_Enum_ANG = 4,
//   ComSquareupProtosCommonCurrencyCode_Enum_AOA = 5,
//   ComSquareupProtosCommonCurrencyCode_Enum_ARS = 6,
//   ComSquareupProtosCommonCurrencyCode_Enum_AUD = 7,
//   ComSquareupProtosCommonCurrencyCode_Enum_AWG = 8,
//   ComSquareupProtosCommonCurrencyCode_Enum_AZN = 9,
//   ComSquareupProtosCommonCurrencyCode_Enum_BAM = 10,
//   ComSquareupProtosCommonCurrencyCode_Enum_BBD = 11,
//   ComSquareupProtosCommonCurrencyCode_Enum_BDT = 12,
//   ComSquareupProtosCommonCurrencyCode_Enum_BGN = 13,
//   ComSquareupProtosCommonCurrencyCode_Enum_BHD = 14,
//   ComSquareupProtosCommonCurrencyCode_Enum_BIF = 15,
//   ComSquareupProtosCommonCurrencyCode_Enum_BMD = 16,
//   ComSquareupProtosCommonCurrencyCode_Enum_BND = 17,
//   ComSquareupProtosCommonCurrencyCode_Enum_BOB = 18,
//   ComSquareupProtosCommonCurrencyCode_Enum_BOV = 19,
//   ComSquareupProtosCommonCurrencyCode_Enum_BRL = 20,
//   ComSquareupProtosCommonCurrencyCode_Enum_BSD = 21,
//   ComSquareupProtosCommonCurrencyCode_Enum_BTN = 22,
//   ComSquareupProtosCommonCurrencyCode_Enum_BWP = 23,
//   ComSquareupProtosCommonCurrencyCode_Enum_BYR = 24,
//   ComSquareupProtosCommonCurrencyCode_Enum_BZD = 25,
//   ComSquareupProtosCommonCurrencyCode_Enum_CAD = 26,
//   ComSquareupProtosCommonCurrencyCode_Enum_CDF = 27,
//   ComSquareupProtosCommonCurrencyCode_Enum_CHE = 28,
//   ComSquareupProtosCommonCurrencyCode_Enum_CHF = 29,
//   ComSquareupProtosCommonCurrencyCode_Enum_CHW = 30,
//   ComSquareupProtosCommonCurrencyCode_Enum_CLF = 31,
//   ComSquareupProtosCommonCurrencyCode_Enum_CLP = 32,
//   ComSquareupProtosCommonCurrencyCode_Enum_CNY = 33,
//   ComSquareupProtosCommonCurrencyCode_Enum_COP = 34,
//   ComSquareupProtosCommonCurrencyCode_Enum_COU = 35,
//   ComSquareupProtosCommonCurrencyCode_Enum_CRC = 36,
//   ComSquareupProtosCommonCurrencyCode_Enum_CUC = 37,
//   ComSquareupProtosCommonCurrencyCode_Enum_CUP = 38,
//   ComSquareupProtosCommonCurrencyCode_Enum_CVE = 39,
//   ComSquareupProtosCommonCurrencyCode_Enum_CZK = 40,
//   ComSquareupProtosCommonCurrencyCode_Enum_DJF = 41,
//   ComSquareupProtosCommonCurrencyCode_Enum_DKK = 42,
//   ComSquareupProtosCommonCurrencyCode_Enum_DOP = 43,
//   ComSquareupProtosCommonCurrencyCode_Enum_DZD = 44,
//   ComSquareupProtosCommonCurrencyCode_Enum_EGP = 45,
//   ComSquareupProtosCommonCurrencyCode_Enum_ERN = 46,
//   ComSquareupProtosCommonCurrencyCode_Enum_ETB = 47,
//   ComSquareupProtosCommonCurrencyCode_Enum_EUR = 48,
//   ComSquareupProtosCommonCurrencyCode_Enum_FJD = 49,
//   ComSquareupProtosCommonCurrencyCode_Enum_FKP = 50,
//   ComSquareupProtosCommonCurrencyCode_Enum_GBP = 51,
//   ComSquareupProtosCommonCurrencyCode_Enum_GEL = 52,
//   ComSquareupProtosCommonCurrencyCode_Enum_GHS = 53,
//   ComSquareupProtosCommonCurrencyCode_Enum_GIP = 54,
//   ComSquareupProtosCommonCurrencyCode_Enum_GMD = 55,
//   ComSquareupProtosCommonCurrencyCode_Enum_GNF = 56,
//   ComSquareupProtosCommonCurrencyCode_Enum_GTQ = 57,
//   ComSquareupProtosCommonCurrencyCode_Enum_GYD = 58,
//   ComSquareupProtosCommonCurrencyCode_Enum_HKD = 59,
//   ComSquareupProtosCommonCurrencyCode_Enum_HNL = 60,
//   ComSquareupProtosCommonCurrencyCode_Enum_HRK = 61,
//   ComSquareupProtosCommonCurrencyCode_Enum_HTG = 62,
//   ComSquareupProtosCommonCurrencyCode_Enum_HUF = 63,
//   ComSquareupProtosCommonCurrencyCode_Enum_IDR = 64,
//   ComSquareupProtosCommonCurrencyCode_Enum_ILS = 65,
//   ComSquareupProtosCommonCurrencyCode_Enum_INR = 66,
//   ComSquareupProtosCommonCurrencyCode_Enum_IQD = 67,
//   ComSquareupProtosCommonCurrencyCode_Enum_IRR = 68,
//   ComSquareupProtosCommonCurrencyCode_Enum_ISK = 69,
//   ComSquareupProtosCommonCurrencyCode_Enum_JMD = 70,
//   ComSquareupProtosCommonCurrencyCode_Enum_JOD = 71,
//   ComSquareupProtosCommonCurrencyCode_Enum_JPY = 72,
//   ComSquareupProtosCommonCurrencyCode_Enum_KES = 73,
//   ComSquareupProtosCommonCurrencyCode_Enum_KGS = 74,
//   ComSquareupProtosCommonCurrencyCode_Enum_KHR = 75,
//   ComSquareupProtosCommonCurrencyCode_Enum_KMF = 76,
//   ComSquareupProtosCommonCurrencyCode_Enum_KPW = 77,
//   ComSquareupProtosCommonCurrencyCode_Enum_KRW = 78,
//   ComSquareupProtosCommonCurrencyCode_Enum_KWD = 79,
//   ComSquareupProtosCommonCurrencyCode_Enum_KYD = 80,
//   ComSquareupProtosCommonCurrencyCode_Enum_KZT = 81,
//   ComSquareupProtosCommonCurrencyCode_Enum_LAK = 82,
//   ComSquareupProtosCommonCurrencyCode_Enum_LBP = 83,
//   ComSquareupProtosCommonCurrencyCode_Enum_LKR = 84,
//   ComSquareupProtosCommonCurrencyCode_Enum_LRD = 85,
//   ComSquareupProtosCommonCurrencyCode_Enum_LSL = 86,
//   ComSquareupProtosCommonCurrencyCode_Enum_LTL = 87,
//   ComSquareupProtosCommonCurrencyCode_Enum_LVL = 88,
//   ComSquareupProtosCommonCurrencyCode_Enum_LYD = 89,
//   ComSquareupProtosCommonCurrencyCode_Enum_MAD = 90,
//   ComSquareupProtosCommonCurrencyCode_Enum_MDL = 91,
//   ComSquareupProtosCommonCurrencyCode_Enum_MGA = 92,
//   ComSquareupProtosCommonCurrencyCode_Enum_MKD = 93,
//   ComSquareupProtosCommonCurrencyCode_Enum_MMK = 94,
//   ComSquareupProtosCommonCurrencyCode_Enum_MNT = 95,
//   ComSquareupProtosCommonCurrencyCode_Enum_MOP = 96,
//   ComSquareupProtosCommonCurrencyCode_Enum_MRO = 97,
//   ComSquareupProtosCommonCurrencyCode_Enum_MUR = 98,
//   ComSquareupProtosCommonCurrencyCode_Enum_MVR = 99,
//   ComSquareupProtosCommonCurrencyCode_Enum_MWK = 100,
//   ComSquareupProtosCommonCurrencyCode_Enum_MXN = 101,
//   ComSquareupProtosCommonCurrencyCode_Enum_MXV = 102,
//   ComSquareupProtosCommonCurrencyCode_Enum_MYR = 103,
//   ComSquareupProtosCommonCurrencyCode_Enum_MZN = 104,
//   ComSquareupProtosCommonCurrencyCode_Enum_NAD = 105,
//   ComSquareupProtosCommonCurrencyCode_Enum_NGN = 106,
//   ComSquareupProtosCommonCurrencyCode_Enum_NIO = 107,
//   ComSquareupProtosCommonCurrencyCode_Enum_NOK = 108,
//   ComSquareupProtosCommonCurrencyCode_Enum_NPR = 109,
//   ComSquareupProtosCommonCurrencyCode_Enum_NZD = 110,
//   ComSquareupProtosCommonCurrencyCode_Enum_OMR = 111,
//   ComSquareupProtosCommonCurrencyCode_Enum_PAB = 112,
//   ComSquareupProtosCommonCurrencyCode_Enum_PEN = 113,
//   ComSquareupProtosCommonCurrencyCode_Enum_PGK = 114,
//   ComSquareupProtosCommonCurrencyCode_Enum_PHP = 115,
//   ComSquareupProtosCommonCurrencyCode_Enum_PKR = 116,
//   ComSquareupProtosCommonCurrencyCode_Enum_PLN = 117,
//   ComSquareupProtosCommonCurrencyCode_Enum_PYG = 118,
//   ComSquareupProtosCommonCurrencyCode_Enum_QAR = 119,
//   ComSquareupProtosCommonCurrencyCode_Enum_RON = 120,
//   ComSquareupProtosCommonCurrencyCode_Enum_RSD = 121,
//   ComSquareupProtosCommonCurrencyCode_Enum_RUB = 122,
//   ComSquareupProtosCommonCurrencyCode_Enum_RWF = 123,
//   ComSquareupProtosCommonCurrencyCode_Enum_SAR = 124,
//   ComSquareupProtosCommonCurrencyCode_Enum_SBD = 125,
//   ComSquareupProtosCommonCurrencyCode_Enum_SCR = 126,
//   ComSquareupProtosCommonCurrencyCode_Enum_SDG = 127,
//   ComSquareupProtosCommonCurrencyCode_Enum_SEK = 128,
//   ComSquareupProtosCommonCurrencyCode_Enum_SGD = 129,
//   ComSquareupProtosCommonCurrencyCode_Enum_SHP = 130,
//   ComSquareupProtosCommonCurrencyCode_Enum_SLL = 131,
//   ComSquareupProtosCommonCurrencyCode_Enum_SOS = 132,
//   ComSquareupProtosCommonCurrencyCode_Enum_SRD = 133,
//   ComSquareupProtosCommonCurrencyCode_Enum_SSP = 134,
//   ComSquareupProtosCommonCurrencyCode_Enum_STD = 135,
//   ComSquareupProtosCommonCurrencyCode_Enum_SVC = 136,
//   ComSquareupProtosCommonCurrencyCode_Enum_SYP = 137,
//   ComSquareupProtosCommonCurrencyCode_Enum_SZL = 138,
//   ComSquareupProtosCommonCurrencyCode_Enum_THB = 139,
//   ComSquareupProtosCommonCurrencyCode_Enum_TJS = 140,
//   ComSquareupProtosCommonCurrencyCode_Enum_TMT = 141,
//   ComSquareupProtosCommonCurrencyCode_Enum_TND = 142,
//   ComSquareupProtosCommonCurrencyCode_Enum_TOP = 143,
//   ComSquareupProtosCommonCurrencyCode_Enum_TRY = 144,
//   ComSquareupProtosCommonCurrencyCode_Enum_TTD = 145,
//   ComSquareupProtosCommonCurrencyCode_Enum_TWD = 146,
//   ComSquareupProtosCommonCurrencyCode_Enum_TZS = 147,
//   ComSquareupProtosCommonCurrencyCode_Enum_UAH = 148,
//   ComSquareupProtosCommonCurrencyCode_Enum_UGX = 149,
//   ComSquareupProtosCommonCurrencyCode_Enum_USD = 150,
//   ComSquareupProtosCommonCurrencyCode_Enum_USN = 151,
//   ComSquareupProtosCommonCurrencyCode_Enum_USS = 152,
//   ComSquareupProtosCommonCurrencyCode_Enum_UYI = 153,
//   ComSquareupProtosCommonCurrencyCode_Enum_UYU = 154,
//   ComSquareupProtosCommonCurrencyCode_Enum_UZS = 155,
//   ComSquareupProtosCommonCurrencyCode_Enum_VEF = 156,
//   ComSquareupProtosCommonCurrencyCode_Enum_VND = 157,
//   ComSquareupProtosCommonCurrencyCode_Enum_VUV = 158,
//   ComSquareupProtosCommonCurrencyCode_Enum_WST = 159,
//   ComSquareupProtosCommonCurrencyCode_Enum_XAF = 160,
//   ComSquareupProtosCommonCurrencyCode_Enum_XAG = 161,
//   ComSquareupProtosCommonCurrencyCode_Enum_XAU = 162,
//   ComSquareupProtosCommonCurrencyCode_Enum_XBA = 163,
//   ComSquareupProtosCommonCurrencyCode_Enum_XBB = 164,
//   ComSquareupProtosCommonCurrencyCode_Enum_XBC = 165,
//   ComSquareupProtosCommonCurrencyCode_Enum_XBD = 166,
//   ComSquareupProtosCommonCurrencyCode_Enum_XCD = 167,
//   ComSquareupProtosCommonCurrencyCode_Enum_XDR = 168,
//   ComSquareupProtosCommonCurrencyCode_Enum_XOF = 169,
//   ComSquareupProtosCommonCurrencyCode_Enum_XPD = 170,
//   ComSquareupProtosCommonCurrencyCode_Enum_XPF = 171,
//   ComSquareupProtosCommonCurrencyCode_Enum_XPT = 172,
//   ComSquareupProtosCommonCurrencyCode_Enum_XTS = 173,
//   ComSquareupProtosCommonCurrencyCode_Enum_XXX = 174,
//   ComSquareupProtosCommonCurrencyCode_Enum_YER = 175,
//   ComSquareupProtosCommonCurrencyCode_Enum_ZAR = 176,
//   ComSquareupProtosCommonCurrencyCode_Enum_ZMK = 177,
//   ComSquareupProtosCommonCurrencyCode_Enum_ZMW = 178,
//   ComSquareupProtosCommonCurrencyCode_Enum_BTC = 179,
// };

// /*!
//  @brief ISO-4217 Currency Codes
//   http://www.currency-iso.org/dl_iso_table_a1.xml
//   Names are the alpha-3 code, ordinals are the numeric code.
//  */
// @interface ComSquareupProtosCommonCurrencyCode : JavaLangEnum < ComSquareupWireWireEnum > {
//  @public
//   JavaLangInteger *cash_rounding_;
//   ComSquareupProtosCommonDenominations *denominations_;
// }

// #pragma mark Public

// /*!
//  @brief Return the constant for <code>value</code> or null.
//  */
// + (ComSquareupProtosCommonCurrencyCode *)fromValueWithInt:(jint)value;

// - (jint)getValue;

// + (ComSquareupProtosCommonCurrencyCode *)valueOfWithNSString:(NSString *)name;

// + (IOSObjectArray *)values;

// @end

// J2OBJC_STATIC_INIT(ComSquareupProtosCommonCurrencyCode)

// /*! INTERNAL ONLY - Use enum accessors declared below. */
// FOUNDATION_EXPORT ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_values_[];

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_AED(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, AED)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_AFN(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, AFN)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_ALL(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, ALL)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_AMD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, AMD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_ANG(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, ANG)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_AOA(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, AOA)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_ARS(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, ARS)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_AUD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, AUD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_AWG(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, AWG)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_AZN(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, AZN)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_BAM(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, BAM)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_BBD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, BBD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_BDT(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, BDT)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_BGN(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, BGN)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_BHD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, BHD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_BIF(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, BIF)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_BMD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, BMD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_BND(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, BND)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_BOB(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, BOB)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_BOV(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, BOV)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_BRL(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, BRL)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_BSD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, BSD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_BTN(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, BTN)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_BWP(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, BWP)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_BYR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, BYR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_BZD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, BZD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_CAD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, CAD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_CDF(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, CDF)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_CHE(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, CHE)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_CHF(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, CHF)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_CHW(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, CHW)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_CLF(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, CLF)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_CLP(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, CLP)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_CNY(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, CNY)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_COP(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, COP)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_COU(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, COU)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_CRC(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, CRC)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_CUC(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, CUC)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_CUP(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, CUP)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_CVE(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, CVE)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_CZK(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, CZK)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_DJF(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, DJF)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_DKK(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, DKK)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_DOP(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, DOP)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_DZD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, DZD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_EGP(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, EGP)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_ERN(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, ERN)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_ETB(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, ETB)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_EUR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, EUR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_FJD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, FJD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_FKP(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, FKP)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_GBP(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, GBP)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_GEL(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, GEL)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_GHS(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, GHS)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_GIP(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, GIP)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_GMD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, GMD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_GNF(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, GNF)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_GTQ(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, GTQ)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_GYD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, GYD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_HKD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, HKD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_HNL(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, HNL)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_HRK(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, HRK)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_HTG(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, HTG)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_HUF(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, HUF)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_IDR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, IDR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_ILS(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, ILS)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_INR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, INR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_IQD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, IQD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_IRR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, IRR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_ISK(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, ISK)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_JMD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, JMD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_JOD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, JOD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_JPY(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, JPY)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_KES(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, KES)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_KGS(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, KGS)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_KHR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, KHR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_KMF(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, KMF)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_KPW(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, KPW)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_KRW(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, KRW)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_KWD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, KWD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_KYD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, KYD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_KZT(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, KZT)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_LAK(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, LAK)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_LBP(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, LBP)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_LKR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, LKR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_LRD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, LRD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_LSL(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, LSL)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_LTL(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, LTL)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_LVL(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, LVL)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_LYD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, LYD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_MAD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, MAD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_MDL(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, MDL)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_MGA(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, MGA)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_MKD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, MKD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_MMK(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, MMK)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_MNT(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, MNT)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_MOP(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, MOP)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_MRO(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, MRO)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_MUR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, MUR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_MVR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, MVR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_MWK(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, MWK)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_MXN(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, MXN)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_MXV(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, MXV)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_MYR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, MYR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_MZN(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, MZN)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_NAD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, NAD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_NGN(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, NGN)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_NIO(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, NIO)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_NOK(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, NOK)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_NPR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, NPR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_NZD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, NZD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_OMR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, OMR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_PAB(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, PAB)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_PEN(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, PEN)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_PGK(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, PGK)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_PHP(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, PHP)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_PKR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, PKR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_PLN(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, PLN)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_PYG(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, PYG)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_QAR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, QAR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_RON(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, RON)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_RSD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, RSD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_RUB(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, RUB)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_RWF(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, RWF)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_SAR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, SAR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_SBD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, SBD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_SCR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, SCR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_SDG(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, SDG)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_SEK(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, SEK)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_SGD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, SGD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_SHP(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, SHP)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_SLL(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, SLL)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_SOS(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, SOS)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_SRD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, SRD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_SSP(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, SSP)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_STD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, STD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_SVC(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, SVC)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_SYP(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, SYP)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_SZL(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, SZL)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_THB(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, THB)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_TJS(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, TJS)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_TMT(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, TMT)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_TND(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, TND)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_TOP(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, TOP)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_TRY(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, TRY)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_TTD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, TTD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_TWD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, TWD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_TZS(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, TZS)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_UAH(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, UAH)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_UGX(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, UGX)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_USD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, USD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_USN(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, USN)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_USS(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, USS)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_UYI(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, UYI)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_UYU(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, UYU)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_UZS(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, UZS)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_VEF(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, VEF)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_VND(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, VND)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_VUV(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, VUV)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_WST(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, WST)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_XAF(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, XAF)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_XAG(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, XAG)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_XAU(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, XAU)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_XBA(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, XBA)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_XBB(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, XBB)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_XBC(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, XBC)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_XBD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, XBD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_XCD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, XCD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_XDR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, XDR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_XOF(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, XOF)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_XPD(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, XPD)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_XPF(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, XPF)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_XPT(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, XPT)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_XTS(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, XTS)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_XXX(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, XXX)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_YER(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, YER)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_ZAR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, ZAR)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_ZMK(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, ZMK)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_ZMW(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, ZMW)

// /*!
//  @brief Currency codes not currently in ISO-4217:
//  */
// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_get_BTC(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupProtosCommonCurrencyCode, BTC)

// J2OBJC_FIELD_SETTER(ComSquareupProtosCommonCurrencyCode, cash_rounding_, JavaLangInteger *)
// J2OBJC_FIELD_SETTER(ComSquareupProtosCommonCurrencyCode, denominations_, ComSquareupProtosCommonDenominations *)

// inline ComSquareupWireProtoAdapter *ComSquareupProtosCommonCurrencyCode_get_ADAPTER(void);
// /*! INTERNAL ONLY - Use accessor function from above. */
// FOUNDATION_EXPORT ComSquareupWireProtoAdapter *ComSquareupProtosCommonCurrencyCode_ADAPTER;
// J2OBJC_STATIC_FIELD_OBJ_FINAL(ComSquareupProtosCommonCurrencyCode, ADAPTER, ComSquareupWireProtoAdapter *)

// FOUNDATION_EXPORT ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_fromValueWithInt_(jint value);

// FOUNDATION_EXPORT IOSObjectArray *ComSquareupProtosCommonCurrencyCode_values(void);

// FOUNDATION_EXPORT ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_valueOfWithNSString_(NSString *name);

// FOUNDATION_EXPORT ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonCurrencyCode_fromOrdinal(NSUInteger ordinal);

// J2OBJC_TYPE_LITERAL_HEADER(ComSquareupProtosCommonCurrencyCode)

// #endif


// #if __has_feature(nullability)
// #pragma clang diagnostic pop
// #endif
// #pragma pop_macro("INCLUDE_ALL_ComSquareupProtosCommonCurrencyCode")
