// //
// //  Generated by the J2ObjC translator.  DO NOT EDIT!
// //  source: None::com/squareup/protos/common/Denominations.java
// //

// #include <J2objcRuntime/J2ObjC_header.h>

// #pragma push_macro("INCLUDE_ALL_ComSquareupProtosCommonDenominations")
// #ifdef RESTRICT_ComSquareupProtosCommonDenominations
// #define INCLUDE_ALL_ComSquareupProtosCommonDenominations 0
// #else
// #define INCLUDE_ALL_ComSquareupProtosCommonDenominations 1
// #endif
// #undef RESTRICT_ComSquareupProtosCommonDenominations

// #if __has_feature(nullability)
// #pragma clang diagnostic push
// #pragma GCC diagnostic ignored "-Wnullability-completeness"
// #endif

// #if !defined (ComSquareupProtosCommonDenominations_) && (INCLUDE_ALL_ComSquareupProtosCommonDenominations || defined(INCLUDE_ComSquareupProtosCommonDenominations))
// #define ComSquareupProtosCommonDenominations_

// #define RESTRICT_ExternalWireWire_runtimeSrcMainJavaComSquareupWireMessage 1
// #define INCLUDE_ComSquareupWireMessage 1
// #include <WireShared/external/wire/wire-runtime/src/main/java/com/squareup/wire/Message.h>

// @class ComSquareupProtosCommonDenominations_Builder;
// @class ComSquareupWireProtoAdapter;
// @class OkioByteString;
// @protocol JavaUtilList;

// @interface ComSquareupProtosCommonDenominations : ComSquareupWireMessage {
//  @public
//   id<JavaUtilList> banknote_cents_;
//   id<JavaUtilList> coin_cents_;
// }

// #pragma mark Public

// - (instancetype __nonnull)initWithJavaUtilList:(id<JavaUtilList>)banknote_cents
//                               withJavaUtilList:(id<JavaUtilList>)coin_cents
//                             withOkioByteString:(OkioByteString *)unknownFields;

// - (jboolean)isEqual:(id)other;

// - (NSUInteger)hash;

// - (ComSquareupProtosCommonDenominations_Builder *)newBuilder OBJC_METHOD_FAMILY_NONE;

// - (NSString *)description;

// - (ComSquareupProtosCommonDenominations *)withoutUnknownFields;

// // Disallowed inherited constructors, do not use.

// - (instancetype __nonnull)initWithComSquareupWireProtoAdapter:(ComSquareupWireProtoAdapter *)arg0
//                                            withOkioByteString:(OkioByteString *)arg1 NS_UNAVAILABLE;

// @end

// J2OBJC_STATIC_INIT(ComSquareupProtosCommonDenominations)

// J2OBJC_FIELD_SETTER(ComSquareupProtosCommonDenominations, banknote_cents_, id<JavaUtilList>)
// J2OBJC_FIELD_SETTER(ComSquareupProtosCommonDenominations, coin_cents_, id<JavaUtilList>)

// inline ComSquareupWireProtoAdapter *ComSquareupProtosCommonDenominations_get_ADAPTER(void);
// /*! INTERNAL ONLY - Use accessor function from above. */
// FOUNDATION_EXPORT ComSquareupWireProtoAdapter *ComSquareupProtosCommonDenominations_ADAPTER;
// J2OBJC_STATIC_FIELD_OBJ_FINAL(ComSquareupProtosCommonDenominations, ADAPTER, ComSquareupWireProtoAdapter *)

// FOUNDATION_EXPORT void ComSquareupProtosCommonDenominations_initWithJavaUtilList_withJavaUtilList_withOkioByteString_(ComSquareupProtosCommonDenominations *self, id<JavaUtilList> banknote_cents, id<JavaUtilList> coin_cents, OkioByteString *unknownFields);

// FOUNDATION_EXPORT ComSquareupProtosCommonDenominations *new_ComSquareupProtosCommonDenominations_initWithJavaUtilList_withJavaUtilList_withOkioByteString_(id<JavaUtilList> banknote_cents, id<JavaUtilList> coin_cents, OkioByteString *unknownFields) NS_RETURNS_RETAINED;

// FOUNDATION_EXPORT ComSquareupProtosCommonDenominations *create_ComSquareupProtosCommonDenominations_initWithJavaUtilList_withJavaUtilList_withOkioByteString_(id<JavaUtilList> banknote_cents, id<JavaUtilList> coin_cents, OkioByteString *unknownFields);

// J2OBJC_TYPE_LITERAL_HEADER(ComSquareupProtosCommonDenominations)

// #endif

// #if !defined (ComSquareupProtosCommonDenominations_Builder_) && (INCLUDE_ALL_ComSquareupProtosCommonDenominations || defined(INCLUDE_ComSquareupProtosCommonDenominations_Builder))
// #define ComSquareupProtosCommonDenominations_Builder_

// #define RESTRICT_ExternalWireWire_runtimeSrcMainJavaComSquareupWireMessage 1
// #define INCLUDE_ComSquareupWireMessage_Builder 1
// #include <WireShared/external/wire/wire-runtime/src/main/java/com/squareup/wire/Message.h>

// @class ComSquareupProtosCommonDenominations;
// @protocol JavaUtilList;

// @interface ComSquareupProtosCommonDenominations_Builder : ComSquareupWireMessage_Builder {
//  @public
//   id<JavaUtilList> banknote_cents_;
//   id<JavaUtilList> coin_cents_;
// }

// #pragma mark Public

// - (instancetype __nonnull)init;

// - (ComSquareupProtosCommonDenominations_Builder *)banknote_centsWithJavaUtilList:(id<JavaUtilList>)banknote_cents;

// - (ComSquareupProtosCommonDenominations *)build;

// - (ComSquareupProtosCommonDenominations_Builder *)coin_centsWithJavaUtilList:(id<JavaUtilList>)coin_cents;

// @end

// J2OBJC_EMPTY_STATIC_INIT(ComSquareupProtosCommonDenominations_Builder)

// J2OBJC_FIELD_SETTER(ComSquareupProtosCommonDenominations_Builder, banknote_cents_, id<JavaUtilList>)
// J2OBJC_FIELD_SETTER(ComSquareupProtosCommonDenominations_Builder, coin_cents_, id<JavaUtilList>)

// FOUNDATION_EXPORT void ComSquareupProtosCommonDenominations_Builder_init(ComSquareupProtosCommonDenominations_Builder *self);

// FOUNDATION_EXPORT ComSquareupProtosCommonDenominations_Builder *new_ComSquareupProtosCommonDenominations_Builder_init(void) NS_RETURNS_RETAINED;

// FOUNDATION_EXPORT ComSquareupProtosCommonDenominations_Builder *create_ComSquareupProtosCommonDenominations_Builder_init(void);

// J2OBJC_TYPE_LITERAL_HEADER(ComSquareupProtosCommonDenominations_Builder)

// #endif


// #if __has_feature(nullability)
// #pragma clang diagnostic pop
// #endif
// #pragma pop_macro("INCLUDE_ALL_ComSquareupProtosCommonDenominations")
