// //
// //  Generated by the J2ObjC translator.  DO NOT EDIT!
// //  source: None::com/squareup/protos/common/Money.java
// //

// #include <J2objcRuntime/J2ObjC_header.h>

// #pragma push_macro("INCLUDE_ALL_ComSquareupProtosCommonMoney")
// #ifdef RESTRICT_ComSquareupProtosCommonMoney
// #define INCLUDE_ALL_ComSquareupProtosCommonMoney 0
// #else
// #define INCLUDE_ALL_ComSquareupProtosCommonMoney 1
// #endif
// #undef RESTRICT_ComSquareupProtosCommonMoney

// #if __has_feature(nullability)
// #pragma clang diagnostic push
// #pragma GCC diagnostic ignored "-Wnullability-completeness"
// #endif

// #if !defined (ComSquareupProtosCommonMoney_) && (INCLUDE_ALL_ComSquareupProtosCommonMoney || defined(INCLUDE_ComSquareupProtosCommonMoney))
// #define ComSquareupProtosCommonMoney_

// #define RESTRICT_ExternalWireWire_runtimeSrcMainJavaComSquareupWireMessage 1
// #define INCLUDE_ComSquareupWireMessage 1
// #include <WireShared/external/wire/wire-runtime/src/main/java/com/squareup/wire/Message.h>

// @class ComSquareupProtosCommonCurrencyCode;
// @class ComSquareupProtosCommonMoney_Builder;
// @class ComSquareupWireProtoAdapter;
// @class JavaLangLong;
// @class OkioByteString;

// /*!
//  @brief Next id: 4
//   See https://git.sqcorp.co/projects/SQ/repos/docs/browse/api/money.md
//  */
// @interface ComSquareupProtosCommonMoney : ComSquareupWireMessage {
//  @public
//   /*!
//    @brief Smallest divisible unit of currency for a given locale,
//   scaled by the default number of decimal places for the currency.
//    For example, amount = 100 in USD means $1.00.
//    */
//   JavaLangLong *amount_;
//   /*!
//    @brief Character string repesenting ISO-4217 currency codes.
//    - seealso: <a href="http://www.currency-iso.org/dl_iso_table_a1.xml">http://www.currency-iso.org/dl_iso_table_a1.xml</a>
//    */
//   ComSquareupProtosCommonCurrencyCode *currency_code_;
// }

// #pragma mark Public

// - (instancetype __nonnull)initWithJavaLangLong:(JavaLangLong *)amount
//        withComSquareupProtosCommonCurrencyCode:(ComSquareupProtosCommonCurrencyCode *)currency_code
//                             withOkioByteString:(OkioByteString *)unknownFields;

// - (jboolean)isEqual:(id)other;

// - (NSUInteger)hash;

// - (ComSquareupProtosCommonMoney_Builder *)newBuilder OBJC_METHOD_FAMILY_NONE;

// - (NSString *)description;

// - (ComSquareupProtosCommonMoney *)withoutUnknownFields;

// // Disallowed inherited constructors, do not use.

// - (instancetype __nonnull)initWithComSquareupWireProtoAdapter:(ComSquareupWireProtoAdapter *)arg0
//                                            withOkioByteString:(OkioByteString *)arg1 NS_UNAVAILABLE;

// @end

// J2OBJC_STATIC_INIT(ComSquareupProtosCommonMoney)

// J2OBJC_FIELD_SETTER(ComSquareupProtosCommonMoney, amount_, JavaLangLong *)
// J2OBJC_FIELD_SETTER(ComSquareupProtosCommonMoney, currency_code_, ComSquareupProtosCommonCurrencyCode *)

// inline ComSquareupWireProtoAdapter *ComSquareupProtosCommonMoney_get_ADAPTER(void);
// /*! INTERNAL ONLY - Use accessor function from above. */
// FOUNDATION_EXPORT ComSquareupWireProtoAdapter *ComSquareupProtosCommonMoney_ADAPTER;
// J2OBJC_STATIC_FIELD_OBJ_FINAL(ComSquareupProtosCommonMoney, ADAPTER, ComSquareupWireProtoAdapter *)

// inline JavaLangLong *ComSquareupProtosCommonMoney_get_DEFAULT_AMOUNT(void);
// /*! INTERNAL ONLY - Use accessor function from above. */
// FOUNDATION_EXPORT JavaLangLong *ComSquareupProtosCommonMoney_DEFAULT_AMOUNT;
// J2OBJC_STATIC_FIELD_OBJ_FINAL(ComSquareupProtosCommonMoney, DEFAULT_AMOUNT, JavaLangLong *)

// inline ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonMoney_get_DEFAULT_CURRENCY_CODE(void);
// /*! INTERNAL ONLY - Use accessor function from above. */
// FOUNDATION_EXPORT ComSquareupProtosCommonCurrencyCode *ComSquareupProtosCommonMoney_DEFAULT_CURRENCY_CODE;
// J2OBJC_STATIC_FIELD_OBJ_FINAL(ComSquareupProtosCommonMoney, DEFAULT_CURRENCY_CODE, ComSquareupProtosCommonCurrencyCode *)

// FOUNDATION_EXPORT void ComSquareupProtosCommonMoney_initWithJavaLangLong_withComSquareupProtosCommonCurrencyCode_withOkioByteString_(ComSquareupProtosCommonMoney *self, JavaLangLong *amount, ComSquareupProtosCommonCurrencyCode *currency_code, OkioByteString *unknownFields);

// FOUNDATION_EXPORT ComSquareupProtosCommonMoney *new_ComSquareupProtosCommonMoney_initWithJavaLangLong_withComSquareupProtosCommonCurrencyCode_withOkioByteString_(JavaLangLong *amount, ComSquareupProtosCommonCurrencyCode *currency_code, OkioByteString *unknownFields) NS_RETURNS_RETAINED;

// FOUNDATION_EXPORT ComSquareupProtosCommonMoney *create_ComSquareupProtosCommonMoney_initWithJavaLangLong_withComSquareupProtosCommonCurrencyCode_withOkioByteString_(JavaLangLong *amount, ComSquareupProtosCommonCurrencyCode *currency_code, OkioByteString *unknownFields);

// J2OBJC_TYPE_LITERAL_HEADER(ComSquareupProtosCommonMoney)

// #endif

// #if !defined (ComSquareupProtosCommonMoney_Builder_) && (INCLUDE_ALL_ComSquareupProtosCommonMoney || defined(INCLUDE_ComSquareupProtosCommonMoney_Builder))
// #define ComSquareupProtosCommonMoney_Builder_

// #define RESTRICT_ExternalWireWire_runtimeSrcMainJavaComSquareupWireMessage 1
// #define INCLUDE_ComSquareupWireMessage_Builder 1
// #include <WireShared/external/wire/wire-runtime/src/main/java/com/squareup/wire/Message.h>

// @class ComSquareupProtosCommonCurrencyCode;
// @class ComSquareupProtosCommonMoney;
// @class JavaLangLong;

// @interface ComSquareupProtosCommonMoney_Builder : ComSquareupWireMessage_Builder {
//  @public
//   JavaLangLong *amount_;
//   ComSquareupProtosCommonCurrencyCode *currency_code_;
// }

// #pragma mark Public

// - (instancetype __nonnull)init;

// /*!
//  @brief Smallest divisible unit of currency for a given locale,
//   scaled by the default number of decimal places for the currency.
//  For example, amount = 100 in USD means $1.00.
//  */
// - (ComSquareupProtosCommonMoney_Builder *)amountWithJavaLangLong:(JavaLangLong *)amount;

// - (ComSquareupProtosCommonMoney *)build;

// /*!
//  @brief Character string repesenting ISO-4217 currency codes.
//  - seealso: <a href="http://www.currency-iso.org/dl_iso_table_a1.xml">http://www.currency-iso.org/dl_iso_table_a1.xml</a>
//  */
// - (ComSquareupProtosCommonMoney_Builder *)currency_codeWithComSquareupProtosCommonCurrencyCode:(ComSquareupProtosCommonCurrencyCode *)currency_code;

// @end

// J2OBJC_EMPTY_STATIC_INIT(ComSquareupProtosCommonMoney_Builder)

// J2OBJC_FIELD_SETTER(ComSquareupProtosCommonMoney_Builder, amount_, JavaLangLong *)
// J2OBJC_FIELD_SETTER(ComSquareupProtosCommonMoney_Builder, currency_code_, ComSquareupProtosCommonCurrencyCode *)

// FOUNDATION_EXPORT void ComSquareupProtosCommonMoney_Builder_init(ComSquareupProtosCommonMoney_Builder *self);

// FOUNDATION_EXPORT ComSquareupProtosCommonMoney_Builder *new_ComSquareupProtosCommonMoney_Builder_init(void) NS_RETURNS_RETAINED;

// FOUNDATION_EXPORT ComSquareupProtosCommonMoney_Builder *create_ComSquareupProtosCommonMoney_Builder_init(void);

// J2OBJC_TYPE_LITERAL_HEADER(ComSquareupProtosCommonMoney_Builder)

// #endif


// #if __has_feature(nullability)
// #pragma clang diagnostic pop
// #endif
// #pragma pop_macro("INCLUDE_ALL_ComSquareupProtosCommonMoney")
