install! 'cocoapods',
  :integrate_targets => false,
  :generate_multiple_pod_projects => true # More performant, see http://blog.cocoapods.org/CocoaPods-1.7.0-beta/#multiple-xcodeproj-generation

use_frameworks!
platform :ios, '16.0'
workspace 'All'

#################
# Binary setup
#################

# Use binaries instead of source code, to speed up builds
$useBinaries = true

if $useBinaries
    plugin 'cocoapods-binary'
    enable_bitcode_for_prebuilt_frameworks!
end

#################
# Third party modules
#################

pod 'SnapKit', '5.6.0', :binary => $useBinaries
pod 'Google-Mobile-Ads-SDK', '10.4.0', :binary => $useBinaries
pod 'GoogleUserMessagingPlatform', '2.0.1', :binary => $useBinaries

#################
# Set swift versions for pods that do not specify them
#################

pre_install do |installer|
  installer.analysis_result.specifications.each do |s|
    s.swift_versions << '5' if s.swift_versions.empty?
  end
end
