// //
// //  Generated by the J2ObjC translator.  DO NOT EDIT!
// //  source: src/main/java/com/squareup/shared/i18n/Key.java
// //

// #include <J2objcRuntime/J2ObjC_header.h>

// #pragma push_macro("INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nKey")
// #ifdef RESTRICT_SrcMainJavaComSquareupSharedI18nKey
// #define INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nKey 0
// #else
// #define INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nKey 1
// #endif
// #undef RESTRICT_SrcMainJavaComSquareupSharedI18nKey

// #if __has_feature(nullability)
// #pragma clang diagnostic push
// #pragma GCC diagnostic ignored "-Wnullability-completeness"
// #endif

// #if !defined (ComSquareupSharedI18nKey_) && (INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nKey || defined(INCLUDE_ComSquareupSharedI18nKey))
// #define ComSquareupSharedI18nKey_

// @class IOSObjectArray;
// @protocol JavaUtilList;

// /*!
//  @brief Stores an Android-iOS key pair for string localization across platforms.
//  */
// @interface ComSquareupSharedI18nKey : NSObject

// #pragma mark Public

// - (instancetype __nonnull)initWithNSString:(NSString *)androidKey
//                               withNSString:(NSString *)iosKey
//                          withNSStringArray:(IOSObjectArray *)tokens;

// - (NSString *)androidKey;

// - (NSString *)iosKey;

// - (id<JavaUtilList>)tokens;

// // Disallowed inherited constructors, do not use.

// - (instancetype __nonnull)init NS_UNAVAILABLE;

// @end

// J2OBJC_EMPTY_STATIC_INIT(ComSquareupSharedI18nKey)

// FOUNDATION_EXPORT void ComSquareupSharedI18nKey_initWithNSString_withNSString_withNSStringArray_(ComSquareupSharedI18nKey *self, NSString *androidKey, NSString *iosKey, IOSObjectArray *tokens);

// FOUNDATION_EXPORT ComSquareupSharedI18nKey *new_ComSquareupSharedI18nKey_initWithNSString_withNSString_withNSStringArray_(NSString *androidKey, NSString *iosKey, IOSObjectArray *tokens) NS_RETURNS_RETAINED;

// FOUNDATION_EXPORT ComSquareupSharedI18nKey *create_ComSquareupSharedI18nKey_initWithNSString_withNSString_withNSStringArray_(NSString *androidKey, NSString *iosKey, IOSObjectArray *tokens);

// J2OBJC_TYPE_LITERAL_HEADER(ComSquareupSharedI18nKey)

// #endif


// #if __has_feature(nullability)
// #pragma clang diagnostic pop
// #endif
// #pragma pop_macro("INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nKey")
