// //
// //  Generated by the J2ObjC translator.  DO NOT EDIT!
// //  source: src/main/java/com/squareup/shared/i18n/LocalizedListHelper.java
// //

// #include <J2objcRuntime/J2ObjC_header.h>

// #pragma push_macro("INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizedListHelper")
// #ifdef RESTRICT_SrcMainJavaComSquareupSharedI18nLocalizedListHelper
// #define INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizedListHelper 0
// #else
// #define INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizedListHelper 1
// #endif
// #undef RESTRICT_SrcMainJavaComSquareupSharedI18nLocalizedListHelper

// #if __has_feature(nullability)
// #pragma clang diagnostic push
// #pragma GCC diagnostic ignored "-Wnullability-completeness"
// #endif

// #if !defined (ComSquareupSharedI18nLocalizedListHelper_) && (INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizedListHelper || defined(INCLUDE_ComSquareupSharedI18nLocalizedListHelper))
// #define ComSquareupSharedI18nLocalizedListHelper_

// @class ComSquareupSharedI18nKey;
// @class IOSObjectArray;
// @protocol ComSquareupSharedI18nLocalizer;

// /*!
//  @brief Wrapper around <code>Localizer</code> to simplify working with lists
//   Note that the put methods must be called in same order that tokens appear in the template string
//   Example 1:
//   Key FRUIT_ONE...// I have a {fruit}.
//  Key FRUITS_TWO... // I have a {fruit_one} and a {fruit_2}.
//   Key FRUITS_MANY... // I have {num_fruit} fruits.
//   fruitsList = LocalizedListHelper.list(localizer,
//    .exactly(1, FRUIT_ONE)
//    .exactly(2, FRUITS_TWO)
//    .orMore(3, FRUITS_MANY));
//   fruitsList.put("banana").put("pear").format()  // prints "I have a banana and a pear."
//   fruitsList.put("banana").put("pear").put("orange").put("apple)   // prints "I have 4 fruits."
//   Example 2:
//   Key LIST_TWO... // {a} and {b}
//   Key LIST_THREE... // {a}, {b} and {c}
//   namesList = LocalizedListHelper.list(localizer,
//    .exactly(1, AS_IS)
//    .exactly(2, LIST_TWO)
//    .exactly(3, LIST_THREE))
//   namesList.put("Bob").format()   // prints "Bob"
//   namesList.put("Bob").put("Mary").format()   // prints "Bob and Mary"
//  */
// @interface ComSquareupSharedI18nLocalizedListHelper : NSObject

// #pragma mark Public

// - (NSString *)format;

// + (ComSquareupSharedI18nLocalizedListHelper *)listWithComSquareupSharedI18nLocalizer:(id<ComSquareupSharedI18nLocalizer>)localizer
//                               withComSquareupSharedI18nLocalizedListHelper_RuleArray:(IOSObjectArray *)keys;

// - (ComSquareupSharedI18nLocalizedListHelper *)putWithInt:(jint)item;

// /*!
//  @brief Puts a list item into the template key, the number of list items determines which template
//   key is used
//  */
// - (ComSquareupSharedI18nLocalizedListHelper *)putWithNSString:(NSString *)item;

// // Disallowed inherited constructors, do not use.

// - (instancetype __nonnull)init NS_UNAVAILABLE;

// @end

// J2OBJC_STATIC_INIT(ComSquareupSharedI18nLocalizedListHelper)

// inline ComSquareupSharedI18nKey *ComSquareupSharedI18nLocalizedListHelper_get_AS_IS(void);
// /*! INTERNAL ONLY - Use accessor function from above. */
// FOUNDATION_EXPORT ComSquareupSharedI18nKey *ComSquareupSharedI18nLocalizedListHelper_AS_IS;
// J2OBJC_STATIC_FIELD_OBJ_FINAL(ComSquareupSharedI18nLocalizedListHelper, AS_IS, ComSquareupSharedI18nKey *)

// FOUNDATION_EXPORT ComSquareupSharedI18nLocalizedListHelper *ComSquareupSharedI18nLocalizedListHelper_listWithComSquareupSharedI18nLocalizer_withComSquareupSharedI18nLocalizedListHelper_RuleArray_(id<ComSquareupSharedI18nLocalizer> localizer, IOSObjectArray *keys);

// J2OBJC_TYPE_LITERAL_HEADER(ComSquareupSharedI18nLocalizedListHelper)

// #endif

// #if !defined (ComSquareupSharedI18nLocalizedListHelper_Rule_) && (INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizedListHelper || defined(INCLUDE_ComSquareupSharedI18nLocalizedListHelper_Rule))
// #define ComSquareupSharedI18nLocalizedListHelper_Rule_

// @class ComSquareupSharedI18nKey;

// @interface ComSquareupSharedI18nLocalizedListHelper_Rule : NSObject

// #pragma mark Public

// + (ComSquareupSharedI18nLocalizedListHelper_Rule *)exactlyWithInt:(jint)quantity
//                                      withComSquareupSharedI18nKey:(ComSquareupSharedI18nKey *)key;

// + (ComSquareupSharedI18nLocalizedListHelper_Rule *)orMoreWithInt:(jint)quantity
//                                     withComSquareupSharedI18nKey:(ComSquareupSharedI18nKey *)key;

// // Disallowed inherited constructors, do not use.

// - (instancetype __nonnull)init NS_UNAVAILABLE;

// @end

// J2OBJC_EMPTY_STATIC_INIT(ComSquareupSharedI18nLocalizedListHelper_Rule)

// FOUNDATION_EXPORT ComSquareupSharedI18nLocalizedListHelper_Rule *ComSquareupSharedI18nLocalizedListHelper_Rule_exactlyWithInt_withComSquareupSharedI18nKey_(jint quantity, ComSquareupSharedI18nKey *key);

// FOUNDATION_EXPORT ComSquareupSharedI18nLocalizedListHelper_Rule *ComSquareupSharedI18nLocalizedListHelper_Rule_orMoreWithInt_withComSquareupSharedI18nKey_(jint quantity, ComSquareupSharedI18nKey *key);

// J2OBJC_TYPE_LITERAL_HEADER(ComSquareupSharedI18nLocalizedListHelper_Rule)

// #endif


// #if __has_feature(nullability)
// #pragma clang diagnostic pop
// #endif
// #pragma pop_macro("INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizedListHelper")
