// //
// //  Generated by the J2ObjC translator.  DO NOT EDIT!
// //  source: src/main/java/com/squareup/shared/i18n/LocalizedStringBuilder.java
// //

// #include <J2objcRuntime/J2ObjC_header.h>

// #pragma push_macro("INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizedStringBuilder")
// #ifdef RESTRICT_SrcMainJavaComSquareupSharedI18nLocalizedStringBuilder
// #define INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizedStringBuilder 0
// #else
// #define INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizedStringBuilder 1
// #endif
// #undef RESTRICT_SrcMainJavaComSquareupSharedI18nLocalizedStringBuilder

// #if __has_feature(nullability)
// #pragma clang diagnostic push
// #pragma GCC diagnostic ignored "-Wnullability-completeness"
// #endif

// #if !defined (ComSquareupSharedI18nLocalizedStringBuilder_) && (INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizedStringBuilder || defined(INCLUDE_ComSquareupSharedI18nLocalizedStringBuilder))
// #define ComSquareupSharedI18nLocalizedStringBuilder_

// /*!
//  @brief Similar to the Phrase class in Android.Currently has implementations to put only
//   a String and an int.
//  If more types need to be interpolated in the future, they can be added here.
//   Used by crossplatform, implemented by Android/iOS.
//  */
// @protocol ComSquareupSharedI18nLocalizedStringBuilder < JavaObject >

// - (NSString *)format;

// - (id<ComSquareupSharedI18nLocalizedStringBuilder>)putWithNSString:(NSString *)token
//                                                       withNSString:(NSString *)value;

// - (id<ComSquareupSharedI18nLocalizedStringBuilder>)putIntWithNSString:(NSString *)token
//                                                               withInt:(jint)value;

// @end

// J2OBJC_EMPTY_STATIC_INIT(ComSquareupSharedI18nLocalizedStringBuilder)

// J2OBJC_TYPE_LITERAL_HEADER(ComSquareupSharedI18nLocalizedStringBuilder)

// #endif


// #if __has_feature(nullability)
// #pragma clang diagnostic pop
// #endif
// #pragma pop_macro("INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizedStringBuilder")
