// //
// //  Generated by the J2ObjC translator.  DO NOT EDIT!
// //  source: src/main/java/com/squareup/shared/i18n/Localizer.java
// //

// #include <J2objcRuntime/J2ObjC_header.h>

// #pragma push_macro("INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizer")
// #ifdef RESTRICT_SrcMainJavaComSquareupSharedI18nLocalizer
// #define INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizer 0
// #else
// #define INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizer 1
// #endif
// #undef RESTRICT_SrcMainJavaComSquareupSharedI18nLocalizer

// #if __has_feature(nullability)
// #pragma clang diagnostic push
// #pragma GCC diagnostic ignored "-Wnullability-completeness"
// #endif

// #if !defined (ComSquareupSharedI18nLocalizer_) && (INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizer || defined(INCLUDE_ComSquareupSharedI18nLocalizer))
// #define ComSquareupSharedI18nLocalizer_

// @class ComSquareupProtosCommonMoney;
// @class ComSquareupSharedI18nKey;
// @class ComSquareupSharedI18nLocalizer_DateTimeType;
// @class ComSquareupSharedI18nLocalizer_MoneyType;
// @class ComSquareupSharedI18nLocalizer_PercentageType;
// @protocol ComSquareupSharedI18nLocalizedStringBuilder;

// /*!
//  @brief Bridge to make crossplatform i18n possible.Used by crossplatform, implemented by Android/iOS
//  */
// @protocol ComSquareupSharedI18nLocalizer < JavaObject >

// /*!
//  @param dateTime ISO-8601 date string in the format of yyyy-MM-dd'T'HH:mm:ssZ,  e.g.: 1997-01-01T06:00:00+00:00
//    Note: Java's SimpleDateFormat leaves off the colon in the time zone. Crossplatform callers
//    should use TimeUtils.asIso8601() to perform the initial Date -
//   >  String conversion.
//  */
// - (NSString *)dateTimeWithNSString:(NSString *)dateTime
// withComSquareupSharedI18nLocalizer_DateTimeType:(ComSquareupSharedI18nLocalizer_DateTimeType *)type;

// - (NSString *)moneyWithComSquareupProtosCommonMoney:(ComSquareupProtosCommonMoney *)money
//        withComSquareupSharedI18nLocalizer_MoneyType:(ComSquareupSharedI18nLocalizer_MoneyType *)type;

// - (NSString *)percentageWithNSString:(NSString *)percentage
// withComSquareupSharedI18nLocalizer_PercentageType:(ComSquareupSharedI18nLocalizer_PercentageType *)type;

// - (id<ComSquareupSharedI18nLocalizedStringBuilder>)stringWithComSquareupSharedI18nKey:(ComSquareupSharedI18nKey *)key;

// - (NSString *)simpleStringWithComSquareupSharedI18nKey:(ComSquareupSharedI18nKey *)key;

// @end

// J2OBJC_EMPTY_STATIC_INIT(ComSquareupSharedI18nLocalizer)

// J2OBJC_TYPE_LITERAL_HEADER(ComSquareupSharedI18nLocalizer)

// #endif

// #if !defined (ComSquareupSharedI18nLocalizer_DateTimeType_) && (INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizer || defined(INCLUDE_ComSquareupSharedI18nLocalizer_DateTimeType))
// #define ComSquareupSharedI18nLocalizer_DateTimeType_

// #define RESTRICT_JavaLangEnum 1
// #define INCLUDE_JavaLangEnum 1
// #include <J2objcRuntime/java/lang/Enum.h>

// @class IOSObjectArray;

// typedef NS_ENUM(NSUInteger, ComSquareupSharedI18nLocalizer_DateTimeType_Enum) {
//   ComSquareupSharedI18nLocalizer_DateTimeType_Enum_SHORT_DATE = 0,
//   ComSquareupSharedI18nLocalizer_DateTimeType_Enum_SHORT_DATE_NO_YEAR = 1,
//   ComSquareupSharedI18nLocalizer_DateTimeType_Enum_MEDIUM_DATE = 2,
//   ComSquareupSharedI18nLocalizer_DateTimeType_Enum_MEDIUM_DATE_NO_YEAR = 3,
//   ComSquareupSharedI18nLocalizer_DateTimeType_Enum_LONG_DATE = 4,
//   ComSquareupSharedI18nLocalizer_DateTimeType_Enum_LONG_DATE_NO_YEAR = 5,
//   ComSquareupSharedI18nLocalizer_DateTimeType_Enum_TIME = 6,
// };

// @interface ComSquareupSharedI18nLocalizer_DateTimeType : JavaLangEnum

// #pragma mark Public

// + (ComSquareupSharedI18nLocalizer_DateTimeType *)valueOfWithNSString:(NSString *)name;

// + (IOSObjectArray *)values;

// @end

// J2OBJC_STATIC_INIT(ComSquareupSharedI18nLocalizer_DateTimeType)

// /*! INTERNAL ONLY - Use enum accessors declared below. */
// FOUNDATION_EXPORT ComSquareupSharedI18nLocalizer_DateTimeType *ComSquareupSharedI18nLocalizer_DateTimeType_values_[];

// inline ComSquareupSharedI18nLocalizer_DateTimeType *ComSquareupSharedI18nLocalizer_DateTimeType_get_SHORT_DATE(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupSharedI18nLocalizer_DateTimeType, SHORT_DATE)

// inline ComSquareupSharedI18nLocalizer_DateTimeType *ComSquareupSharedI18nLocalizer_DateTimeType_get_SHORT_DATE_NO_YEAR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupSharedI18nLocalizer_DateTimeType, SHORT_DATE_NO_YEAR)

// inline ComSquareupSharedI18nLocalizer_DateTimeType *ComSquareupSharedI18nLocalizer_DateTimeType_get_MEDIUM_DATE(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupSharedI18nLocalizer_DateTimeType, MEDIUM_DATE)

// inline ComSquareupSharedI18nLocalizer_DateTimeType *ComSquareupSharedI18nLocalizer_DateTimeType_get_MEDIUM_DATE_NO_YEAR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupSharedI18nLocalizer_DateTimeType, MEDIUM_DATE_NO_YEAR)

// inline ComSquareupSharedI18nLocalizer_DateTimeType *ComSquareupSharedI18nLocalizer_DateTimeType_get_LONG_DATE(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupSharedI18nLocalizer_DateTimeType, LONG_DATE)

// inline ComSquareupSharedI18nLocalizer_DateTimeType *ComSquareupSharedI18nLocalizer_DateTimeType_get_LONG_DATE_NO_YEAR(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupSharedI18nLocalizer_DateTimeType, LONG_DATE_NO_YEAR)

// inline ComSquareupSharedI18nLocalizer_DateTimeType *ComSquareupSharedI18nLocalizer_DateTimeType_get_TIME(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupSharedI18nLocalizer_DateTimeType, TIME)

// FOUNDATION_EXPORT IOSObjectArray *ComSquareupSharedI18nLocalizer_DateTimeType_values(void);

// FOUNDATION_EXPORT ComSquareupSharedI18nLocalizer_DateTimeType *ComSquareupSharedI18nLocalizer_DateTimeType_valueOfWithNSString_(NSString *name);

// FOUNDATION_EXPORT ComSquareupSharedI18nLocalizer_DateTimeType *ComSquareupSharedI18nLocalizer_DateTimeType_fromOrdinal(NSUInteger ordinal);

// J2OBJC_TYPE_LITERAL_HEADER(ComSquareupSharedI18nLocalizer_DateTimeType)

// #endif

// #if !defined (ComSquareupSharedI18nLocalizer_MoneyType_) && (INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizer || defined(INCLUDE_ComSquareupSharedI18nLocalizer_MoneyType))
// #define ComSquareupSharedI18nLocalizer_MoneyType_

// #define RESTRICT_JavaLangEnum 1
// #define INCLUDE_JavaLangEnum 1
// #include <J2objcRuntime/java/lang/Enum.h>

// @class IOSObjectArray;

// typedef NS_ENUM(NSUInteger, ComSquareupSharedI18nLocalizer_MoneyType_Enum) {
//   ComSquareupSharedI18nLocalizer_MoneyType_Enum_DEFAULT = 0,
//   ComSquareupSharedI18nLocalizer_MoneyType_Enum_SHORTER = 1,
//   ComSquareupSharedI18nLocalizer_MoneyType_Enum_CENTS = 2,
// };

// @interface ComSquareupSharedI18nLocalizer_MoneyType : JavaLangEnum

// #pragma mark Public

// + (ComSquareupSharedI18nLocalizer_MoneyType *)valueOfWithNSString:(NSString *)name;

// + (IOSObjectArray *)values;

// @end

// J2OBJC_STATIC_INIT(ComSquareupSharedI18nLocalizer_MoneyType)

// /*! INTERNAL ONLY - Use enum accessors declared below. */
// FOUNDATION_EXPORT ComSquareupSharedI18nLocalizer_MoneyType *ComSquareupSharedI18nLocalizer_MoneyType_values_[];

// inline ComSquareupSharedI18nLocalizer_MoneyType *ComSquareupSharedI18nLocalizer_MoneyType_get_DEFAULT(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupSharedI18nLocalizer_MoneyType, DEFAULT)

// inline ComSquareupSharedI18nLocalizer_MoneyType *ComSquareupSharedI18nLocalizer_MoneyType_get_SHORTER(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupSharedI18nLocalizer_MoneyType, SHORTER)

// inline ComSquareupSharedI18nLocalizer_MoneyType *ComSquareupSharedI18nLocalizer_MoneyType_get_CENTS(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupSharedI18nLocalizer_MoneyType, CENTS)

// FOUNDATION_EXPORT IOSObjectArray *ComSquareupSharedI18nLocalizer_MoneyType_values(void);

// FOUNDATION_EXPORT ComSquareupSharedI18nLocalizer_MoneyType *ComSquareupSharedI18nLocalizer_MoneyType_valueOfWithNSString_(NSString *name);

// FOUNDATION_EXPORT ComSquareupSharedI18nLocalizer_MoneyType *ComSquareupSharedI18nLocalizer_MoneyType_fromOrdinal(NSUInteger ordinal);

// J2OBJC_TYPE_LITERAL_HEADER(ComSquareupSharedI18nLocalizer_MoneyType)

// #endif

// #if !defined (ComSquareupSharedI18nLocalizer_PercentageType_) && (INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizer || defined(INCLUDE_ComSquareupSharedI18nLocalizer_PercentageType))
// #define ComSquareupSharedI18nLocalizer_PercentageType_

// #define RESTRICT_JavaLangEnum 1
// #define INCLUDE_JavaLangEnum 1
// #include <J2objcRuntime/java/lang/Enum.h>

// @class IOSObjectArray;

// typedef NS_ENUM(NSUInteger, ComSquareupSharedI18nLocalizer_PercentageType_Enum) {
//   ComSquareupSharedI18nLocalizer_PercentageType_Enum_DEFAULT = 0,
//   ComSquareupSharedI18nLocalizer_PercentageType_Enum_TAX = 1,
//   ComSquareupSharedI18nLocalizer_PercentageType_Enum_DISCOUNT = 2,
//   ComSquareupSharedI18nLocalizer_PercentageType_Enum_WHOLE_NUMBER = 3,
// };

// @interface ComSquareupSharedI18nLocalizer_PercentageType : JavaLangEnum

// #pragma mark Public

// + (ComSquareupSharedI18nLocalizer_PercentageType *)valueOfWithNSString:(NSString *)name;

// + (IOSObjectArray *)values;

// @end

// J2OBJC_STATIC_INIT(ComSquareupSharedI18nLocalizer_PercentageType)

// /*! INTERNAL ONLY - Use enum accessors declared below. */
// FOUNDATION_EXPORT ComSquareupSharedI18nLocalizer_PercentageType *ComSquareupSharedI18nLocalizer_PercentageType_values_[];

// inline ComSquareupSharedI18nLocalizer_PercentageType *ComSquareupSharedI18nLocalizer_PercentageType_get_DEFAULT(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupSharedI18nLocalizer_PercentageType, DEFAULT)

// inline ComSquareupSharedI18nLocalizer_PercentageType *ComSquareupSharedI18nLocalizer_PercentageType_get_TAX(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupSharedI18nLocalizer_PercentageType, TAX)

// inline ComSquareupSharedI18nLocalizer_PercentageType *ComSquareupSharedI18nLocalizer_PercentageType_get_DISCOUNT(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupSharedI18nLocalizer_PercentageType, DISCOUNT)

// inline ComSquareupSharedI18nLocalizer_PercentageType *ComSquareupSharedI18nLocalizer_PercentageType_get_WHOLE_NUMBER(void);
// J2OBJC_ENUM_CONSTANT(ComSquareupSharedI18nLocalizer_PercentageType, WHOLE_NUMBER)

// FOUNDATION_EXPORT IOSObjectArray *ComSquareupSharedI18nLocalizer_PercentageType_values(void);

// FOUNDATION_EXPORT ComSquareupSharedI18nLocalizer_PercentageType *ComSquareupSharedI18nLocalizer_PercentageType_valueOfWithNSString_(NSString *name);

// FOUNDATION_EXPORT ComSquareupSharedI18nLocalizer_PercentageType *ComSquareupSharedI18nLocalizer_PercentageType_fromOrdinal(NSUInteger ordinal);

// J2OBJC_TYPE_LITERAL_HEADER(ComSquareupSharedI18nLocalizer_PercentageType)

// #endif


// #if __has_feature(nullability)
// #pragma clang diagnostic pop
// #endif
// #pragma pop_macro("INCLUDE_ALL_SrcMainJavaComSquareupSharedI18nLocalizer")
