// //
// //  Generated by the J2ObjC translator.  DO NOT EDIT!
// //  source: None::com/google/protobuf/EnumValueOptions.java
// //

// #include <J2objcRuntime/J2ObjC_header.h>

// #pragma push_macro("INCLUDE_ALL_ComGoogleProtobufEnumValueOptions")
// #ifdef RESTRICT_ComGoogleProtobufEnumValueOptions
// #define INCLUDE_ALL_ComGoogleProtobufEnumValueOptions 0
// #else
// #define INCLUDE_ALL_ComGoogleProtobufEnumValueOptions 1
// #endif
// #undef RESTRICT_ComGoogleProtobufEnumValueOptions

// #if __has_feature(nullability)
// #pragma clang diagnostic push
// #pragma GCC diagnostic ignored "-Wnullability-completeness"
// #endif

// #if !defined (ComGoogleProtobufEnumValueOptions_) && (INCLUDE_ALL_ComGoogleProtobufEnumValueOptions || defined(INCLUDE_ComGoogleProtobufEnumValueOptions))
// #define ComGoogleProtobufEnumValueOptions_

// #define RESTRICT_ExternalWireWire_runtimeSrcMainJavaComSquareupWireMessage 1
// #define INCLUDE_ComSquareupWireMessage 1
// #include <WireShared/external/wire/wire-runtime/src/main/java/com/squareup/wire/Message.h>

// @class ComGoogleProtobufEnumValueOptions_Builder;
// @class ComSquareupProtosCommonDenominations;
// @class ComSquareupWireProtoAdapter;
// @class JavaLangInteger;
// @class OkioByteString;

// @interface ComGoogleProtobufEnumValueOptions : ComSquareupWireMessage {
//  @public
//   /*!
//    @brief Extension source: squareup/common/currency_codes.proto
//    */
//   JavaLangInteger *cash_rounding_;
//   /*!
//    @brief Extension source: squareup/common/currency_codes.proto
//    */
//   ComSquareupProtosCommonDenominations *denominations_;
// }

// #pragma mark Public

// - (instancetype __nonnull)initWithJavaLangInteger:(JavaLangInteger *)cash_rounding
//          withComSquareupProtosCommonDenominations:(ComSquareupProtosCommonDenominations *)denominations;

// - (instancetype __nonnull)initWithJavaLangInteger:(JavaLangInteger *)cash_rounding
//          withComSquareupProtosCommonDenominations:(ComSquareupProtosCommonDenominations *)denominations
//                                withOkioByteString:(OkioByteString *)unknownFields;

// - (jboolean)isEqual:(id)other;

// - (NSUInteger)hash;

// - (ComGoogleProtobufEnumValueOptions_Builder *)newBuilder OBJC_METHOD_FAMILY_NONE;

// - (NSString *)description;

// - (ComGoogleProtobufEnumValueOptions *)withoutUnknownFields;

// // Disallowed inherited constructors, do not use.

// - (instancetype __nonnull)initWithComSquareupWireProtoAdapter:(ComSquareupWireProtoAdapter *)arg0
//                                            withOkioByteString:(OkioByteString *)arg1 NS_UNAVAILABLE;

// @end

// J2OBJC_STATIC_INIT(ComGoogleProtobufEnumValueOptions)

// J2OBJC_FIELD_SETTER(ComGoogleProtobufEnumValueOptions, cash_rounding_, JavaLangInteger *)
// J2OBJC_FIELD_SETTER(ComGoogleProtobufEnumValueOptions, denominations_, ComSquareupProtosCommonDenominations *)

// inline ComSquareupWireProtoAdapter *ComGoogleProtobufEnumValueOptions_get_ADAPTER(void);
// /*! INTERNAL ONLY - Use accessor function from above. */
// FOUNDATION_EXPORT ComSquareupWireProtoAdapter *ComGoogleProtobufEnumValueOptions_ADAPTER;
// J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleProtobufEnumValueOptions, ADAPTER, ComSquareupWireProtoAdapter *)

// inline JavaLangInteger *ComGoogleProtobufEnumValueOptions_get_DEFAULT_CASH_ROUNDING(void);
// /*! INTERNAL ONLY - Use accessor function from above. */
// FOUNDATION_EXPORT JavaLangInteger *ComGoogleProtobufEnumValueOptions_DEFAULT_CASH_ROUNDING;
// J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleProtobufEnumValueOptions, DEFAULT_CASH_ROUNDING, JavaLangInteger *)

// FOUNDATION_EXPORT void ComGoogleProtobufEnumValueOptions_initWithJavaLangInteger_withComSquareupProtosCommonDenominations_(ComGoogleProtobufEnumValueOptions *self, JavaLangInteger *cash_rounding, ComSquareupProtosCommonDenominations *denominations);

// FOUNDATION_EXPORT ComGoogleProtobufEnumValueOptions *new_ComGoogleProtobufEnumValueOptions_initWithJavaLangInteger_withComSquareupProtosCommonDenominations_(JavaLangInteger *cash_rounding, ComSquareupProtosCommonDenominations *denominations) NS_RETURNS_RETAINED;

// FOUNDATION_EXPORT ComGoogleProtobufEnumValueOptions *create_ComGoogleProtobufEnumValueOptions_initWithJavaLangInteger_withComSquareupProtosCommonDenominations_(JavaLangInteger *cash_rounding, ComSquareupProtosCommonDenominations *denominations);

// FOUNDATION_EXPORT void ComGoogleProtobufEnumValueOptions_initWithJavaLangInteger_withComSquareupProtosCommonDenominations_withOkioByteString_(ComGoogleProtobufEnumValueOptions *self, JavaLangInteger *cash_rounding, ComSquareupProtosCommonDenominations *denominations, OkioByteString *unknownFields);

// FOUNDATION_EXPORT ComGoogleProtobufEnumValueOptions *new_ComGoogleProtobufEnumValueOptions_initWithJavaLangInteger_withComSquareupProtosCommonDenominations_withOkioByteString_(JavaLangInteger *cash_rounding, ComSquareupProtosCommonDenominations *denominations, OkioByteString *unknownFields) NS_RETURNS_RETAINED;

// FOUNDATION_EXPORT ComGoogleProtobufEnumValueOptions *create_ComGoogleProtobufEnumValueOptions_initWithJavaLangInteger_withComSquareupProtosCommonDenominations_withOkioByteString_(JavaLangInteger *cash_rounding, ComSquareupProtosCommonDenominations *denominations, OkioByteString *unknownFields);

// J2OBJC_TYPE_LITERAL_HEADER(ComGoogleProtobufEnumValueOptions)

// #endif

// #if !defined (ComGoogleProtobufEnumValueOptions_Builder_) && (INCLUDE_ALL_ComGoogleProtobufEnumValueOptions || defined(INCLUDE_ComGoogleProtobufEnumValueOptions_Builder))
// #define ComGoogleProtobufEnumValueOptions_Builder_

// #define RESTRICT_ExternalWireWire_runtimeSrcMainJavaComSquareupWireMessage 1
// #define INCLUDE_ComSquareupWireMessage_Builder 1
// #include <WireShared/external/wire/wire-runtime/src/main/java/com/squareup/wire/Message.h>

// @class ComGoogleProtobufEnumValueOptions;
// @class ComSquareupProtosCommonDenominations;
// @class JavaLangInteger;

// @interface ComGoogleProtobufEnumValueOptions_Builder : ComSquareupWireMessage_Builder {
//  @public
//   JavaLangInteger *cash_rounding_;
//   ComSquareupProtosCommonDenominations *denominations_;
// }

// #pragma mark Public

// - (instancetype __nonnull)init;

// - (ComGoogleProtobufEnumValueOptions *)build;

// - (ComGoogleProtobufEnumValueOptions_Builder *)cash_roundingWithJavaLangInteger:(JavaLangInteger *)cash_rounding;

// - (ComGoogleProtobufEnumValueOptions_Builder *)denominationsWithComSquareupProtosCommonDenominations:(ComSquareupProtosCommonDenominations *)denominations;

// @end

// J2OBJC_EMPTY_STATIC_INIT(ComGoogleProtobufEnumValueOptions_Builder)

// J2OBJC_FIELD_SETTER(ComGoogleProtobufEnumValueOptions_Builder, cash_rounding_, JavaLangInteger *)
// J2OBJC_FIELD_SETTER(ComGoogleProtobufEnumValueOptions_Builder, denominations_, ComSquareupProtosCommonDenominations *)

// FOUNDATION_EXPORT void ComGoogleProtobufEnumValueOptions_Builder_init(ComGoogleProtobufEnumValueOptions_Builder *self);

// FOUNDATION_EXPORT ComGoogleProtobufEnumValueOptions_Builder *new_ComGoogleProtobufEnumValueOptions_Builder_init(void) NS_RETURNS_RETAINED;

// FOUNDATION_EXPORT ComGoogleProtobufEnumValueOptions_Builder *create_ComGoogleProtobufEnumValueOptions_Builder_init(void);

// J2OBJC_TYPE_LITERAL_HEADER(ComGoogleProtobufEnumValueOptions_Builder)

// #endif


// #if __has_feature(nullability)
// #pragma clang diagnostic pop
// #endif
// #pragma pop_macro("INCLUDE_ALL_ComGoogleProtobufEnumValueOptions")
